theme: jekyll-theme-primer

# Exclude directories and files from processing
exclude:
  - node_modules
  - server/node_modules
  - my-mariadb-app/node_modules
  - .git
  - .gitignore
  - vendor
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - package.json
  - tsconfig.json
